name: Tails with Ngrok

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      ngrok:
        image: wernight/ngrok
        ports:
          - 22:22
        options: --region=us --hostname=localhost
    steps:
      - uses: actions/checkout@v2

      - name: Start Tails
        run: |
          docker run -d --name tails tailscale/tailscale
          sleep 10s
          docker exec -it tails /bin/bash -c "tailscale up"

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          echo ${{ secrets.NGROK_AUTH_TOKEN }} | ./ngrok authtoken -

      - name: Connect to Ngrok
        run: |
          nohup ./ngrok tcp 22 &
