name: SSH to Ubuntu with Ngrok
on: [push]

env:
  # Set the time in seconds for how long you want the workflow to run
  TIMEOU: 21600

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ngrok
        run: |
          echo 'root:root' | sudo chpasswd
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/
          ngrok authtoken 1vnsyS5WyJJl4DRyQpsbtrv89uR_351cgadRbV8NU9aqBV1Ut
          
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start SSH and Ngrok
        run: |
          sudo apt-get install -y openssh-server
          sudo sed -i 's/#PasswordAuthentication/PasswordAuthentication/g' /etc/ssh/sshd_config
          sudo service ssh restart
          ngrok tcp 22 > /dev/null & 
      - name: Generate SSH key
        run: ssh-keygen -t rsa -b 4096 -C "my@zorilith.online" -N "" -f ~/.ssh/id_rsa

      - name: Print public key
        run: cat ~/.ssh/id_rsa.pub

      - name: Wait for timeout
        run: sleep $TIMEOU
